resource "scaleway_registry_namespace" "main" {
  name        = "crn-shared-${var.environment}-scr-lz-fr-par"
  description = "Registry Namespace for landingzone - ${var.environment}"
  is_public   = false
  project_id  = data.scaleway_account_project.default_project.id
}

resource "scaleway_account_project" "product_project" {
  for_each = {
    for product_environment in local.product_environments : product_environment.product_environment => product_environment if product_environment.needs_scaleway
  }

  name = "${each.key}-${each.value.location}"

  lifecycle {
    prevent_destroy = true
  }
}

resource "scaleway_iam_application" "application_project" {
  for_each = {
    for product_environment in local.product_environments : product_environment.product_environment => product_environment if product_environment.needs_scaleway
  }

  name        = "app-${each.key}-spn"
  description = "Application for ${each.key}"
}

resource "scaleway_iam_policy" "product_project_policy" {
  for_each = {
    for product_environment in local.product_environments : product_environment.product_environment => product_environment if product_environment.needs_scaleway
  }

  name           = "project-policy-${each.key}-AllProductsFullAccess"
  application_id = scaleway_iam_application.application_project[each.key].id

  rule {
    project_ids          = [scaleway_account_project.product_project[each.key].id]
    permission_set_names = ["AllProductsFullAccess"]
  }
}

resource "scaleway_iam_policy" "product_container_registry_policy" {
  for_each = {
    for product_environment in local.product_environments : product_environment.product_environment => product_environment if product_environment.needs_scaleway
  }

  name           = "project-policy-${each.key}-registry-full-access"
  application_id = scaleway_iam_application.application_project[each.key].id

  rule {
    project_ids          = [data.scaleway_account_project.default_project.id]
    permission_set_names = ["ContainerRegistryFullAccess"]
  }
}

resource "scaleway_iam_api_key" "main" {
  for_each = {
    for product_environment in local.product_environments : product_environment.product_environment => product_environment if product_environment.needs_scaleway
  }

  application_id     = scaleway_iam_application.application_project[each.key].id
  description        = "API key for product application"
  default_project_id = scaleway_account_project.product_project[each.key].id
  expires_at         = "2026-06-29T10:43:29Z"
}

resource "scaleway_iam_api_key" "state_api_key" {
  for_each = {
    for product_environment in local.product_environments : product_environment.product_environment => product_environment if product_environment.needs_scaleway
  }

  application_id     = scaleway_iam_application.application_project[each.key].id
  description        = "API key for state management"
  default_project_id = data.scaleway_account_project.default_project.id
  expires_at         = "2026-06-29T10:43:29Z"
}

// Output credentials on GitHub repos

resource "github_repository" "product_repository" {
  for_each = { for product in var.Products : product.ProductName => product }

  name               = "TGC.${each.value.ProductName}"
  description        = "Repository for ${each.value.ProductName}. Auto-generated by Landingzone."
  visibility         = "public"
  allow_squash_merge = true
  allow_rebase_merge = false
  allow_merge_commit = false

  template {
    owner                = "aatrisgn"
    repository           = "default_repository"
    include_all_branches = true
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "github_actions_secret" "secret_organization_id" {
  for_each = {
    for product_environment in local.product_environments : product_environment.product_environment => product_environment if product_environment.needs_scaleway
  }

  #Should directly reference repositories
  repository      = "TGC.${each.value.product_name}"
  secret_name     = "${replace(each.key, "-", "_")}_organization_id"
  plaintext_value = var.organization_id

  depends_on = [github_repository.product_repository]
}

resource "github_actions_secret" "secret_project_id" {
  for_each = {
    for product_environment in local.product_environments : product_environment.product_environment => product_environment if product_environment.needs_scaleway
  }

  #Should directly reference repositories
  repository      = "TGC.${each.value.product_name}"
  secret_name     = "${replace(each.key, "-", "_")}_project_id"
  plaintext_value = scaleway_account_project.product_project[each.key].id

  depends_on = [github_repository.product_repository]
}

resource "github_actions_secret" "deployment_access_key" {
  for_each = {
    for product_environment in local.product_environments : product_environment.product_environment => product_environment if product_environment.needs_scaleway
  }

  #Should directly reference repositories
  repository      = "TGC.${each.value.product_name}"
  secret_name     = "${replace(each.key, "-", "_")}_deployment_access_key"
  plaintext_value = scaleway_iam_api_key.main[each.key].access_key

  depends_on = [github_repository.product_repository]
}

resource "github_actions_secret" "deployment_secret_access_key" {
  for_each = {
    for product_environment in local.product_environments : product_environment.product_environment => product_environment if product_environment.needs_scaleway
  }

  #Should directly reference repositories
  repository      = "TGC.${each.value.product_name}"
  secret_name     = "${replace(each.key, "-", "_")}_deployment_secret_access_key"
  plaintext_value = scaleway_iam_api_key.main[each.key].secret_key

  depends_on = [github_repository.product_repository]
}

resource "github_actions_secret" "state_access_key" {
  for_each = {
    for product_environment in local.product_environments : product_environment.product_environment => product_environment if product_environment.needs_scaleway
  }

  #Should directly reference repositories
  repository      = "TGC.${each.value.product_name}"
  secret_name     = "${replace(each.key, "-", "_")}_state_access_key"
  plaintext_value = scaleway_iam_api_key.state_api_key[each.key].access_key

  depends_on = [github_repository.product_repository]
}

resource "github_actions_secret" "state_secret_access_key" {
  for_each = {
    for product_environment in local.product_environments : product_environment.product_environment => product_environment if product_environment.needs_scaleway
  }

  #Should directly reference repositories
  repository      = "TGC.${each.value.product_name}"
  secret_name     = "${replace(each.key, "-", "_")}_state_secret_access_key"
  plaintext_value = scaleway_iam_api_key.state_api_key[each.key].secret_key

  depends_on = [github_repository.product_repository]
}

resource "github_actions_secret" "state_bucket_name" {
  for_each = {
    for product_environment in local.product_environments : product_environment.product_environment => product_environment if product_environment.needs_scaleway
  }

  #Should directly reference repositories
  repository      = "TGC.${each.value.product_name}"
  secret_name     = "${replace(each.key, "-", "_")}_state_bucket_name"
  plaintext_value = var.bucket_name

  depends_on = [github_repository.product_repository]
}