terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.15.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.0.0"
    }
  }
}

# Configure the GitHub Provider
provider "github" {}

# Configure the Azure Active Directory Provider
provider "azuread" {
  tenant_id = "SOME"
}

provider "azurerm" {
  features {}
}

resource "github_repository" "product_repository" {
    for_each = { for product in var.Products : product.Name => env }
    name = "TGC.${each.value.Name}"
    description = "Repository for ${each.value.Name}. Auto-generated by Landingzone."
    visibility = "public"
}

resource "azurerm_resource_group" "product_environment_group" {
    for_each = {
        for product in var.Products : product.ProductName => {
            for env in product.Environments : "${product.ProductName}" => env 
        } 
    }

    name = "rg-${each.key}-${each.value.Type}-${each.value.Location}"
    location = each.value.Location
    tags = {
      "provision" = "landingzones"
    }
}

resource "azuread_application" "product_environment_spns" {
    for_each = {
        for product in var.Products : product.ProductName => {
            for env in product.Environments : "${product.ProductName}" => env 
        } 
    }

    display_name = "${each.key}-${each.value.Type}-SPN"
}

resource "azurerm_role_assignment" "product_environment_owner" {
    for_each = azuread_service_principal.product_environment_spn

    scope = azurerm_resource_group.product_environment_group[each.key].id
    role_definition_name = "Owner"
    principal_id = each.value.object_id
}