name: Build TGC.GithubSecretConsole

on:
  push:
    branches: ["main"]
    paths:
    - '.github/workflows/BuildGithubSecretConsole.yml'
    - 'src/TGC.GitHubSecretConsole/**'
  pull_request:
    branches: ["main"]
    paths:
    - '.github/workflows/BuildGithubSecretConsole.yml'
    - 'src/TGC.GitHubSecretConsole/**'
  workflow_dispatch:

jobs:
    build_job:
        runs-on: ubuntu-latest
        env:
            projectPath: src/TGC.GitHubSecretConsole/TGC.GitHubSecretConsole/TGC.GitHubSecretConsole.csproj
            testProjectPath: src/TGC.GitHubSecretConsole/TGC.GitHubSecretConsole.Tests/TGC.GitHubSecretConsole.Tests.csproj
    
        steps:
        - uses: actions/checkout@v3
    
        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.5   
        
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x

        - name: Restore dependencies
          run: dotnet restore $projectPath

        - name: Build
          run: dotnet build $projectPath --no-restore
        
        - name: Test
          run: dotnet test $testProjectPath