on:
  push:
    branches: ["main"]
    paths:
    - '!.github/workflows/BuildGithubSecretConsole.yml'
    - '!src/TGC.GitHubSecretConsole/**'
  pull_request:
    branches: ["main"]
    paths:
    - '!.github/workflows/BuildGithubSecretConsole.yml'
    - '!src/TGC.GitHubSecretConsole/**'
  workflow_dispatch:

name: 'Landing Zone Deployment'

jobs:
  create_landingzone:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main
    - name: Log in with Azure

      uses: azure/login@v1
      with:
        creds: '${{ secrets.LANDINGZONE_CREDENTIALS }}'
        enable-AzPSSession: true

    # - name: 'Deploy Infrastructure'
    #   uses: azure/CLI@v1
    #   with:
    #     inlineScript: |
    #       az deployment tenant create \
    #       --name subscriptionDeployment \
    #       --location westeurope \
    #       --template-file src/bicep/LandingZone.bicep \
    #       --parameters subscriptionName=LandingZoneDeployment billingAccountId='${{ secrets.BILLING_ACCOUNT_ID }}' billingProfileId='${{ secrets.BILLING_PROFILE_ID }}' invoiceSectionId=${{ secrets.INVOICE_SECTION_ID }} managementGroupId=LandingZoneManagementGroup

    - name: Create GitHub repository
      shell: pwsh
      run: |
        .github/scripts/CreateRepository.ps1 -authToken '${{ secrets.LANDINGZONE_TOKEN }}' -repositoryName 'SomeRepository123'

    - name: Create subscription
      shell: pwsh
      run: |
        .github/scripts/CreateAzureSubscription.ps1 -authToken '${{ secrets.LANDINGZONE_TOKEN }}' -repositoryName 'SomeRepository'

    - name: Checkout private repo
      uses: actions/checkout@v2
      with:
        repository: aatrisgn/SomeRepository
        token: ${{ secrets.LANDINGZONE_TOKEN }}
        path: templateRepository

    - name: Add template files
      shell: pwsh
      run: |
        .github/scripts/CreateRepository.ps1 -authToken '${{ secrets.LANDINGZONE_TOKEN }}' -repositoryName 'SomeRepository'

    - name: Create SPN
      shell: pwsh
      run: |
        .github/scripts/getChangedFiles.ps1 -modulesDirectory '${{ github.workspace }}/BicepModules' -targetDirectory '${{ runner.temp }}/UpdatedModules'

    - name: Add SPN as ServiceConnection
      shell: pwsh
      run: |
        .github/scripts/getChangedFiles.ps1 -modulesDirectory '${{ github.workspace }}/BicepModules' -targetDirectory '${{ runner.temp }}/UpdatedModules'
