name: Deploy Landing Zones

on:
  push:
    branches: ["main"]
    paths:
        - "terraform/landingzone/*"
        - ".github/workflows/deploy_landingzone.yml"
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      applyTF:
        description: 'Apply TF plan?'
        required: true
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  LANDING_ZONE_FILE_NAME: "landingzone.json"

jobs:
  plan_landingzones:
    name: "Plan landingzone deployment"
    runs-on: ubuntu-latest
    environment: prd
    defaults:
      run:
        working-directory: ./terraform/landingzone
    
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      ARM_USE_AZUREAD: true
      ENV_NAME: "prd"
      GITHUB_TOKEN: "${{ secrets.TF_GITHUB_TOKEN }}"
      #TF_LOG: INFO

    steps:
    - uses: actions/checkout@v3

    - name: Install Terraform
      run: bash "${{ github.workspace }}/.github/scripts/install_terraform.sh" 

    - name: Terraform Fmt
      run: terraform fmt -check

    - name: Generate landingzone var file
      shell: pwsh
      run: |
        ${{ github.workspace }}/.github/scripts/combine_landingzone_json.ps1 -rootFolder "${{ github.workspace }}/Landingzones" -outputFilePath "${{ github.workspace }}/terraform/landingzone/${{ env.LANDING_ZONE_FILE_NAME }}"

    - name: Terraform Init
      run: |
        terraform init \
        -backend-config=resource_group_name="${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
        -backend-config=storage_account_name="${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
        -backend-config=container_name="${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}" \
        -backend-config=key="landingzone.prd.tfstate"
        
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -var-file=${{ env.LANDING_ZONE_FILE_NAME }} -var-file='environments/${{ env.ENV_NAME }}/vars.tfvars' -var=tenant_id="${{ secrets.AZURE_TENANT_ID }}"

  deploy_landingzones:
    runs-on: ubuntu-latest
    environment: prd
    name: "Apply landingzone deployment"
    needs: plan_landingzones
    if: github.event.inputs.applyTF == 'true' && github.event_name != 'push' && github.event_name != 'pull_request'
    defaults:
      run:
        working-directory: ./terraform/landingzone
    
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      ARM_USE_AZUREAD: true
      GITHUB_TOKEN: "${{ secrets.TF_GITHUB_TOKEN }}"
      ENV_NAME: "prd"

    steps:
    - uses: actions/checkout@v3

    - name: Install Terraform
      run: bash "${{ github.workspace }}/.github/scripts/install_terraform.sh"
    
    - name: Generate landingzone var file
      shell: pwsh
      run: |
        ${{ github.workspace }}/.github/scripts/combine_landingzone_json.ps1 -rootFolder "${{ github.workspace }}/Landingzones" -outputFilePath "${{ github.workspace }}/terraform/landingzone/${{ env.LANDING_ZONE_FILE_NAME }}"

    - name: Terraform Init
      run: |
        terraform init \
        -backend-config=resource_group_name="${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
        -backend-config=storage_account_name="${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
        -backend-config=container_name="${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}" \
        -backend-config=key="landingzone.prd.tfstate"
        
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -var-file=${{ env.LANDING_ZONE_FILE_NAME }} -var-file='environments/${{ env.ENV_NAME }}/vars.tfvars' -var=tenant_id="${{ secrets.AZURE_TENANT_ID }}" -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
    