on:
  push:
    branches: ["main"]
    paths:
    - '.github/workflows/DNSConfiguration.yml'
    - 'bicep/frontdoorDeployment.bicep'
  pull_request:
    branches: ["main"]
    paths:
    - '.github/workflows/DNSConfiguration.yml'
  workflow_dispatch:

name: 'DNS Configuration Deployment'

permissions:
  id-token: write
  contents: read

jobs:
  Configure-DEV-DNS:
    name: Configure DEV Routing
    environment: production
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Azure OIDC Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_WIF_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_WIF_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_WIF_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Build
      shell: pwsh
      run: |
        .github/scripts/CompileApplicationDNSZones.ps1 -Environment DEV

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_WIF_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_LANDINGZONE_RG }}
        template: bicep/frontdoorDeployment.bicep
        parameters: 'bicep/parameters/applicationDNSZones.parameters.DEV.json'
        failOnStdErr: false

  Configure-STA-DNS:
    needs: Configure-DEV-DNS
    name: Configure STA Routing
    environment: production
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Azure OIDC Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_WIF_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_WIF_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_WIF_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Build
      shell: pwsh
      run: |
        .github/scripts/CompileApplicationDNSZones.ps1 -Environment STA

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_WIF_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_LANDINGZONE_RG }}
        template: bicep/frontdoorDeployment.bicep
        parameters: 'bicep/parameters/applicationDNSZones.parameters.STA.json'
        failOnStdErr: false

  Configure-PRD-DNS:
    needs: Configure-STA-DNS
    name: Configure PRD Routing
    environment: production
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Azure OIDC Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_WIF_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_WIF_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_WIF_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Build
      shell: pwsh
      run: |
        .github/scripts/CompileApplicationDNSZones.ps1 -Environment PRD

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_WIF_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_LANDINGZONE_RG }}
        template: bicep/frontdoorDeployment.bicep
        parameters: 'bicep/parameters/applicationDNSZones.parameters.PRD.json'
        failOnStdErr: false
